const works = [
  {
    work_id: 30,
    desc: "Ca sáng",
    key: "T8",
    value: "11:00 - 11:30",
    active: false,
    disabled: false,
    available: false,
  },
  {
    work_id: 35,
    desc: "Ca chiều",
    key: "T13",
    value: "13:30 - 14:00",
    active: false,
    disabled: false,
    available: false,
  },
  {
    work_id: 38,
    desc: "Ca chiều",
    key: "T16",
    value: "15:00 - 15:30",
    active: false,
    disabled: false,
    available: true,
  },
  {
    work_id: 41,
    desc: "Ca chiều",
    key: "T19",
    value: "16:30 - 17:00",
    active: false,
    disabled: false,
    available: false,
  },
  {
    work_id: 40,
    desc: "Ca chiều",
    key: "T18",
    value: "16:00 - 16:30",
    active: false,
    disabled: false,
    available: false,
  },
  {
    work_id: 37,
    desc: "Ca chiều",
    key: "T15",
    value: "14:30 - 15:00",
    active: false,
    disabled: false,
    available: false,
  },
  {
    work_id: 36,
    desc: "Ca chiều",
    key: "T14",
    value: "14:00 - 14:30",
    active: false,
    disabled: false,
    available: false,
  },
  {
    work_id: 39,
    desc: "Ca chiều",
    key: "T17",
    value: "15:30 - 16:00",
    active: false,
    disabled: false,
    available: false,
  },
];
